# Generated by Django 5.1.1 on 2025-12-22 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0022_alter_titlebutton_options_titlebutton_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='record_action_buttons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
