# Generated by Django 5.1.1 on 2026-01-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0022_alter_titlebutton_options_titlebutton_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='titlebutton',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='component',
            name='order',
        ),
        migrations.RemoveField(
            model_name='titlebutton',
            name='order',
        ),
    ]
