# Generated by Django 5.1.1 on 2025-12-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0022_alter_titlebutton_options_titlebutton_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='tour_id',
            field=models.CharField(blank=True, help_text='Optional tour ID for quick tours', max_length=100, null=True),
        ),
    ]
