# Generated by Django 5.1.1 on 2026-01-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0023_alter_component_options_alter_titlebutton_options_and_more'),
        ('copo_core', '0023_profiletype_record_action_buttons'),
    ]

    operations = [
    ]
