# Generated by Django 5.1.1 on 2026-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0024_merge_20260126_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletype',
            name='record_action_buttons',
        ),
        migrations.AddField(
            model_name='profiletype',
            name='action_buttons',
            field=models.ManyToManyField(blank=True, to='copo_core.recordactionbutton'),
        ),
    ]
