# Generated by Django 5.1.1 on 2026-02-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0023_profiletype_tour_id'),
        ('copo_core', '0025_remove_profiletype_record_action_buttons_and_more'),
    ]

    operations = [
    ]
